# Directs the Travis CI build service for Web WorldWind
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Set up to run the JavaScript build script per the Travis CI documentation
language: node_js

# Configure the build to use the latest Node.js 6.x release
node_js:
  - "6"

# Build the project. Travis CI automatically runs npm install before the build
script:
  - npm run build

# Deploy build artifacts. Travis does not invoke this step for pull request builds
deploy:
  # Publish release distributions to the Artifactory repository
  - provider: script
    script: echo ${TRAVIS_TAG#"v"}
    skip_cleanup: true
    on:
      tags: true

# Node.js build cache configuration. See the Travis CI documentation: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-npm
cache:
  directories:
    - "node_modules"
